4장 정리(style)
GDSC-SKHU/Core-JavaScript pull request #50
Opened 2023-02-08 07:08 UTC by Lee2Eunji

2023-02-08 07:54 UTC, hyesungoh commented
이 PR은 #49 가 머지되고 나서 되면 좋겠네요 ~

2023-02-08 07:54 UTC, hyesungoh approved these changes

2023-02-08 07:55 UTC, hyesungoh requested changes
~~#49 요 PR이 아직 머지되기 전이니,~~
~~이 PR 변경 내용을 #49 에서 사용한 브랜치에 추가하면 됩니다~~

제가 착각했네요!!

2023-02-08 15:39 UTC, hyesungoh approved these changes

2023-02-08 15:39 UTC, lgyn10 approved these changes

2023-02-09 09:00 UTC, yuj2n approved these changes

2023-02-09 13:16 UTC, merged